from time import sleep
print("In this game, the words written in all caps (LIKE THIS) are possible actions, type them when prompted to give your answer to each scenario.")
sleep(5)
print("However, you may try other actions than the ones provided, but the result may be less than ideal...")
sleep(3)
print("Your adventure begins...")
sleep(1)
print("You live in a farming village, life is peaceful. Today is a bright sunny day, do you...")
sleep(1)
print("Go to WORK")
sleep(0.5)
print("STAY home")
sleep(0.5)
print("Take a WALK")
ch1=input("???: ")
if ch1.lower()=="work":
    print("You go to work in your fields, with hoe in hand you begin tilling for the season. Nearby you hear shouting, looking up you see three rough looking men attacking your neighbor, do you...")
    sleep(1)
    print("Help FIGHT the vagabonds off")
    sleep(0.5)
    print("Help the vagabonds ROB your neighbor")
    sleep(0.5)
    print("RUN away and get help")
    ch2a=input("???: ")
    sleep(1)
    if ch2a.lower()=="fight":
        print("With hoe in hand, you spring into action. You have the element of surprise on your side, but it looks like they've already hurt your neighbor, do you...")
        sleep(1)
        print("SNEAK up slowly and catch them by surprise")
        sleep(0.5)
        print("Attack with HASTE")
        sleep(0.5)
        print("LOSE interest")
        ch3aa=input("???: ")
        if ch3aa.lower()=="sneak":
            print("You sneak up slowly and carefully as your neighbor is getting beaten. When you're close enough you swing your hoe and strike the largest of the three in the head. He falls over, unconscious to the ground. The other two stare blankly in shock and surprise, taking your chance you swing again, knocking a second out cold. The third runs away. Do you...")
            sleep(1)
            print("CHASE the third robber down")
            sleep(0.5)
            print("TEND to your neighbors injuries")
            sleep(0.5)
            print("LEAVE")
            ch4aaa=input("???: ")
            if ch4aaa.lower()=="chase":
                print("You run after the third robber. You're quick but he runs at about the same speed. This little foot race is a stalemate, he may even get away. Do you...")
                sleep(1)
                print("THROW the hoe")
                sleep(0.5)
                print("Keep RUN-ning")
                ch5aaa=input("???: ")
                if ch5aaa.lower()=="throw":
                    print("You heft your hoe up over your shoulder. As if it were a javelin you throw it forward. No evil doer is escaping your grasp. The hoe hits the robber in the back of the leg and he falls to the ground, rolling several times. You easily catch up now amd you're standing above him. Do you...")
                    sleep(1)
                    print("FINISH him off")
                    sleep(0.5)
                    print("INTIM-idate him")
                    sleep(0.5)
                    print("LEAVE")
                    ch6aaa=input("???: ")
                    if ch6aaa.lower()=="finish":
                        print("You pick your hoe back up from where it landed, with a single strike to the head, the vagabond is no more.")
                        sleep(2)
                        print("Game Complete! You got the'Vengeful Protector' ending. Evil will not be allowed to exist with you around...")
                    elif ch6aaa.lower()=="intim":
                        print("You pick your hoe back up from where it landed, with a single strike near the head, you make a hole in the mud next to his ear. 'NEVER come back here, if I see you again, I'll do far worse'. The mad nods wordlessly, you stand back allowing him to get up. He runs and you kick him hard as he runs away.")
                        sleep(7)
                        print("Game Complete! You got the 'Protector' ending. Your courage is an example to all. Well done!")
                    elif ch6aaa.lower()=="leave":
                        print("You're nearly out of breath, and you probably weren't goin to catch him anyway. What you did to his partners should be enough to get the message through his head. Time to get back home")
                        sleep(5)
                        print("Game Complete! You got the 'Defensive Stance' ending. You attack evil in range, follow for a little while, and return to your original post.")
                    else:
                        print("You keep chasing, but somehow lose sight of him. Infact, you don't recognize any of your surroundings, it's as if you somehow moved a great distance without knowing, to a place you've never even been before")
                        sleep(7)
                        print("You move around a bit to try and get your bearings, but no matter where you go, you see nothing. No trees, no houses, no people, just rollings hills for miles, as far as the eye can see. Do you...")
                        sleep(7)
                        print("PICK a direction and move until you find something")
                        sleep(0.5)
                        print("SIT and wait until someone finds you")
                        sleep(0.5)
                        print("MAKE an appeal to a higher power")
                        ch7e=input("???: ")
                        if ch7e.lower()=="pick":
                            print("You move for what feels like miles, what seems like days. The strange thing is, you never tire, you never hunger, and the sun never moves. But you keep moving. Weeks pass, months, years, decades perhaps, you don't know.")
                            sleep(10)
                            print("You forget about the robbers, about your neighbor, you even forget your own name. At some point all you can remember is that, for some reason, you need to keeo moving forward, and so you do. You move forward, untiring and unthinking, forever...")
                            sleep(10)
                            print("game complete... you got the 'purgatory' ending...")
                            sleep(0.1)
                            print("...")
                            sleep(0.1)
                            print(".....")
                            sleep(0.1)
                            print(".......")
                            sleep(0.1)
                            print(".........")
                            sleep(0.1)
                            print("...........")
                            sleep(0.1)
                            print(".............")
                            sleep(0.1)
                            print("...............")
                            sleep(0.1)
                            print(".................")
                            sleep(0.1)
                            print("...................")
                            sleep(0.1)
                            print(".....................")
                        elif ch7e.lower()=="sit":
                            print("You sit for what seems like days. The strange thing is, you never thirst, you never hunger, and the sun never moves. But you keep sitting. Weeks pass, months, years, decades perhaps, you don't know.")
                            sleep(10)
                            print("You forget about the robbers, about your neighbor, you even forget your own name. At some point all you can remember is that, for some reason, you need to keeo sitting here, and so you do. You sit, untiring and unthinking, forever...")
                            sleep(10)
                            print("game complete... you got the 'other purgatory' ending...")
                            sleep(0.1)
                            print("...")
                            sleep(0.1)
                            print(".....")
                            sleep(0.1)
                            print(".......")
                            sleep(0.1)
                            print(".........")
                            sleep(0.1)
                            print("...........")
                            sleep(0.1)
                            print(".............")
                            sleep(0.1)
                            print("...............")
                            sleep(0.1)
                            print(".................")
                            sleep(0.1)
                            print("...................")
                            sleep(0.1)
                            print(".....................")
                        elif ch7e.lower()=="make":
                            print("After searching for something to aid you, a reason for your being here, you give up, you need help. You shout to the monochromatic heavens for help...")
                            sleep(12)
                            print("No Answer......")
                            sleep(10)
                            print("game complete... you got the 'only purgatory' ending...")
                        else:
                            print("This is it")
                            sleep(3)
                            print("Don't you get it????")
                            sleep(3)
                            print("This is what happens when you take doors other than that which have been presented to you")
                            sleep(5)
                            print("You lose......")
                            sleep(5)
                            print("Game Over: refresh to try again....")
                elif ch5aaa.lower()=="run":
                    print("You keep chasing for a while, until you're both well out of town. After a while you start to catch up. Having worked in the fields for a living rather than steeling to get by, your body is accustomed to work. Finally you have him close enough to grab and you do.")
                    sleep(10)
                    print("He turns to face you and fights back, grabbing onto you in the same way. Do you...")
                    sleep(1)
                    print("WRESTLE")
                    sleep(0.5)
                    print("STRIKE")
                    ch6aab=input("???: ")
                else:
                    print("The robber escapes, your neighbor bleeds out, you see that you've done nothing of value and your heart breaks")
                    sleep(3)
                    print("You die on the spot")
                    sleep(0.5)
                    print("You have died: GAME OVER")
            elif ch4aaa.lower()=="tend":
                print("The third man runs and escapes alone. You stay behind and inspect the physical state of your neighbor. He's bleeding from his head and it seems like one of his ribs may be broken. You're not a doctor but you bandage him up as best as you can. He's breathing heavily and clearly in a lot of pain, but he's able to stand. He reaching out a wobbly hand for a shake and says, 'You may have just saved my life there, I owe you a great debt'. Do you...")
                sleep(1)
                print("Say 'YES, you do' ")
                sleep(0.5)
                print("Say 'I'm just glad you're OK' ")
                ch5aab=input("???: ")
                if ch5aab.lower()=="yes":
                    print("You're rewarded with a lard amount of gold, which obviously you deserve, you're a hero and you deserve a hero's reward")
                    sleep(5)
                    print("Game Complete! You got the 'Hero's Reward' ending. Those who can't protect themselves, cough up says you.")
                elif ch5aab.lower()=="ok":
                    print("You've done a great deed today, and as a result you make a great friend. Over the coming years and coming hardships, your neighbor never forgets how you saved him. He helps you when you're in need, and as is your nature, you do the same for him.")
                    sleep(7)
                    print("Game Complete! You got the 'Love thy Neighbor' ending. You're truly a good person!")
            elif ch4aaa.lower()=="leave":
                print("Your neighbor is alive, the threat is gone, not much need to do anymore. Besides, you were busy before this whole ordeal, your fields need plowing and your neighbor will be fine.")
                sleep(10)
                print("You get back to work tilling the land")
                sleep(3)
                print("Game Complete! You got the 'Unfeeling Protector' ending. There are worse ways to finish the game I guess...")
            else:
                print("That choice was really dumb, like, really really. Don't you know what happens when you don't follow the path layed out for you....")
                sleep(7)
                print("Game Over.....")
        elif ch3aa.lower()=="haste":
            print("You charge in with a shout, litterally leaping at the nearest man. Your shout gets their attention and two of them turn to face you. Since you acted so quickly, your neighbor is not hurt badly. He punches the one still holding him in the nose and you're sure you heard in break. The other two robbers' attention is split now, and in the confusion, you and your neighbor easily take them down. All three run away with a limp.")
            sleep(10)
            print("Your neighbor speaks 'You may have just saved my life there, come inside, I'll pour you a drink")
            sleep(5)
            print("Your neighbor thanks you with a mug of ale and a handful of gold from his secret stash, the two of you are much closer now as friends")
            sleep(5)
            print("Game Complete! You got the 'Good Samaritan' ending. You did what any good person would, well done.")
        elif ch3aa.lower()=="lose":
            print("You stare on for a moment, but having worked so hard today, you begin to get tired. Sitting down on the grass, you quickly fall asleep")
            sleep(5)
            print("When you wake up, you look again and see your neighbor, bruised and limping, picking up his belongings that have clearly been thrown around by the vagabonds. He gives you a dirty scowl and turns away")
            sleep(5)
            print("Game Complete. You got the 'Sociopath' ending. Not a care in the world eh?")
        else:
            print("You do your best with the decision you've made, but unfortunately it's very very illegal")
            sleep(3)
            print("You're apprehended by the police and thrown in jail")
            sleep(3)
            print("After a VERY short trial, you're sentenced to death by fall height")
            sleep(3)
            print("The next day, two burly guards throw you off a cliff while snobbish nobles applaud and guffaw")
            sleep(3)
            print("You die on the spot")
            sleep(0.5)
            print("You have died: GAME OVER")
    elif ch2a.lower()=="rob":
        print("With hoe in hand, you spring into action. You hit your neighbor on his head, knocking him out. The robbers seem surprised, but they also laugh. You now ransack the house along side the three of them. During the search, you find a hidden hatch under a rug. Turns out your neighbor had a chest full of gold hidden away! Do you...")
        sleep(1)
        print("HIDE the chest, to keep it for yourself")
        sleep(0.5)
        print("SHOW the robbers your find")
        sleep(0.5)
        print("IGNORE the chest and keep ransacking the house")
        ch3ab=input("???: ")
        if ch3ab.lower()=="hide":
            print("You replace the rug and pretend to keep searching. They find a few things here and there and distribute it amongst the four of you (you notice your share is a bit smaller as they leave).")
            sleep(7)
            print("Once they're out of sight, you take up the rug once more and remove the chest, hurrying back to your house you open it and count it up")
            sleep(5)
            print("It's a pretty large amount, but far from life changing money")
            sleep(3)
            print("Game Complete. You got the 'Petty Thief' ending. Was it really worth the guilt?")
        elif ch3ab.lower()=="show":
            print("You show the other men your findings. Nodding at each other, one of them pulls out an knife and stabs you through the heart")
            sleep(3)
            print("You're dead before you can really process what has happened")
            sleep(2)
            print("Game Complete. You got the 'Betrayed' ending. No honor among thieves, remember that...")
        elif ch3ab.lower()=="ignore":
            print("You leave the chest uncovered but leave it alone. As is to be expected, one of the others finds it soon after. Very quickly the three of them get into an argument about how to divide the gold up. The argument gets loud and angry. Do you...")
            sleep(1)
            print("SNEAK away to avoid confrontation")
            sleep(0.5)
            print("JOIN the argument to try and get a share")
            sleep(0.5)
            print("GRAB the chest and run")
            ch4aba=input("???: ")
            if ch4aba.lower()=="sneak":
                print("You sneak away safely. You can still hear the shouting for several meters as you make your way back to your house. Things resolve (although you aren't sure how) and return to normal. For the rest of the time you live here, your neighbor is always giving you mean looks and avoiding speaking to you whenever he can.")
                sleep(5)
                print("Game Complete. You got the 'Crime Don't Pay' ending. You've done a bad thing for absolutely no reason. You suck.")
            elif ch4aba.lower()=="join":
                print("You begin yelling along with them, but as soon as you do, all three of them turn to face you. 'Who do you think YOU are? We only let you hand around because we thought you were funny'. Without another word, you're stabbed right through the gut")
                sleep(10)
                print("Avarice never pays off")
                sleep(2)
                print("You have died: GAME OVER")
            elif ch4aba.lower()=="grab":
                print("With one hand you grab the chest and tuck it under your arm, with the other, you shove the one holding it hard into one of the others, and with that, you take off running. The vagabonds give chase but you, having worked for a living rather than stealing to get by, are more durable. You're able to escape with the chest and after laying low for a few days, you return home and enjoy your gold")
                sleep(10)
                print("Game Complete! You got the 'Crime Pays' ending. Money is money, get it however you can.")
            else:
                print("You make an attempt to do this, but the argument gets too loud. Not only do you lose focus, but their voices reach over 200 decibels.")
                sleep(5)
                print("Your eardrums burst, as do your lungs, as does your heart.")
                sleep(3)
                print("You die on the spot")
                sleep(0.5)
                print("You have died: GAME OVER")
        else:
            print("As you act, a bolt of lightning strikes you in the chest. Strange, last you checked there wasn't a cloud in the sky...")
            sleep(3)
            print("You die on the spot")
            sleep(0.5)
            print("You have died: GAME OVER")
    elif ch2a.lower()=="run":
        print("You run for help, gathering as a few people who you believe can handle themselves in a fight. However, by the time you get back, it's too late. Your neighbor is hurt and unconscious, and his house is ransacked, do you...")
        sleep(1)
        print("TEND to the injuries of your neighbor")
        sleep(0.5)
        print("SEARCH for where the robbers went")
        sleep(0.5)
        print("LOSE interest")
        ch3ac=input("???: ")
        if ch3ac.lower()=="tend":
            print("The townsfolk search for anything that may tell them where the robbers went, but don't find much. While they do this, you're making sure that your neighbor is ok. He's bleeding from his head and you're pretty sure one of his ribs is broken, but once you bandage him up, you're sure he'll be ok.")
            sleep(5)
            print("Once you've finished with him, you get him into his house and make sure he's comfortable. He thanks you for healing him, but is clearly bitter about what's happened to his house. 'Please go, I'd like to be alone now', he says with a sigh.")
            sleep(5)
            print("Game Complete. You got the 'Unfortunate Happenstance' ending. You tried to help, but the robbers won in the end.")
        elif ch3ac.lower()=="search":
            print("You give your neighbor a quick glance, 'he's hurt but he'll probably be fine', you think to yourself. Right now what's more important is that justice is done to the men who did this to him. You look around, but find nothing. No footprints, no clues of any kind. Silently you curse the fact that it's the middle ages and finger print ID technology won't be invented for several hundered years, 'would have been handy' you think.")
            sleep(10)
            print("During the search, somone notices that your neighbors injuries were worse than you'd thought. You try to save him, but now it's too late. He's lost too much blood and he isn't going to make it. 'If only the IV drip had been invented' you think. But it's too late.")
            sleep(7)
            print("Game Complete. You got the 'Unfortunate Day' ending. Things could have turned out differently if only you lived in a day with better technology.")
        elif ch3ac.lower()=="lose":
            print("It's too late really, there's nothing you can do now, may as well go home and make the most out of the rest of the day. Your neighbor will probably be fine anyway, he's merely the victim of unfortunate circumstance.")
            sleep(5)
            print("Game Complete. You got the 'Not my Problem' ending. Oh well.")
        else:
            print("It doesn't work")
    else:
        print("You made a very silly choice, you are a very silly person")
        sleep(3)
        print("You die on the spot")
        sleep(0.5)
        print("You have died: GAME OVER")
elif ch1.lower()=="stay":
    print("You stay home and make yourself a nice breakfast. You relax with a book, eventually falling back asleep. You don't wake up as three men enter your house. You don't wake up until they have your hands bound. Unable to move, you watch as they ransack your house, taking anything of value, do you...")
    sleep(1)
    print("STRUGGLE against the restraints")
    sleep(0.5)
    print("WAIT and watch")
    sleep(0.5)
    print("YELL for help")
    ch2b=input("???: ")
    if ch2b.lower()=="struggle":
        print("You fight hard on the rope, doing your best to keep it discreet so your attackers won't know. Eventually you get one hand free, with that one you are easily able to loose the other. You are free! do you...")
        sleep(1)
        print("ATTACK the robbers")
        sleep(0.5)
        print("RUN away")
        sleep(0.5)
        print("TICKLE the closest robber")
        ch3ba=input("???: ")
        if ch3ba.lower()=="attack":
            print("You're strong and you have the element of surprise on your hand. You throw a good solid punch to one robber, putting him on the ground, with great speed, you punch the next robber, causing him to clutch his nose in pain. The third picks up a chair and swings it around towards you, but you're quick.")
            sleep(7)
            print("You catch the chair and sparta kick the man holding it in the chest, he's sent stumbling backwards and lands on his back, only one left. With chair in hand, you hit him on the head, breaking the chair and causing him to fall.")
            sleep(7)
            print("You now stand over three men on your floor, victorious. 'LEAVE, GET OUT NOW', you roar at them. With haste, they stand and leave, not looking back. Now that all is well, you resume your nap.")
            sleep(7)
            print("Game Complete! You got the 'Castle Doctrine' ending. This is your house, you must defend it.")
        elif ch3ba.lower()=="run":
            print("They've left the door open, so you take your chance and run. You run to your neighbors house for help, but you find his house in ramshackles and him beaten down in the front doorway. Do you...")
            sleep(5)
            print("TRY to save him")
            sleep(0.5)
            print("SEEK help elsewhere")
            ch4baa=input("???: ")
        elif ch3ba.lower()=="tickle":
            print("You spring into action, putting your hands on the nearest robber. You startle them and they brandish knives, but before they can react fully, you begin tickling. The robber cackles and squirms, falling over onto the ground, but you don't relent. He laughs and rolls around, 'HAHA STOP, I CAN'T TAKE IT HAHAHA' he screams.")
            sleep(10)
            print("Finally you stop, springing quickly at the second robber, giving him the same treatment and getting the same reaction. You repeat the process for the third and after you've finished, they're all still laughing and smiling. They hug each other and open up the circle for you to join, obviously you hug them.")
            sleep(10)
            print("They see the error of their ways and turn away from their life of crime. Just as well, they become close friends with you. Every year they come back to the village and spend christmas with you. Whenever you're in trouble, they always come to help. It's a wonderful ending to a scary day.")
            sleep(7)
            print("Game Complete! You got the 'Friendship is Magic' ending. How beautiful.")
        else:
            print("You make an attempt, but as you do so, you get a nasty splinter from your chair. Since you live in the middle ages, it gets an infection which immediately spreads to your entire body.")
            sleep(5)
            print("You die on the spot")
            sleep(0.5)
            print("You have died: GAME OVER")
    elif ch2b.lower()=="wait":
        print("You sit still and watch as your personal things are tossed around, the vagabonds looking for aything valuable. Having not found much, the biggest of the three gets close and say's, angrily, 'I know you're hiding something somewhere, so where is it', how do you answer? ")
        sleep(1)
        print("remain SILENT")
        sleep(0.5)
        print("TELL him what he wants to know")
        sleep(0.5)
        print("SPIT in his face")
        ch3bb=input("???: ")
    elif ch2b.lower()=="yell":
        print("You yell loudly, calling out for anyone that can hear you. One of the three men walk over and punch you right across your face. You're in pain, your vision is blurry. One of them draws a knife from a sheath and moves towards you. It seems as though this is the end, but just in time, several people from the town burst through the door.")
        sleep(10)
        print("The robbers are well outnumbered now and the people wrestle them each to the ground, tying their hands behind their backs. At the same time, someone comes over and undoes your bonds. Upon asking, it turns out your neighbor was robbed as well, so when they heard you yelling, they came to save you from the same fate as he suffered.")
        sleep(7)
        print("The vagabonds are thrown in jail, and you're safe. A memorial is held for your neighbor and despite not knowing him all that well, you attend. Things are gloomy for a while, but they return to normal within a few weeks.")
        sleep(5)
        print("Game Complete. You got the 'Good of the People' ending. We live in a society (:")
    else:
        print("The choice you made would have been successful and all would be right in the town")
        sleep(0.5)
        print("Unfortunately you suffer a fatal heart attack at that exact moment")
        sleep(3)
        print("You die on the spot")
        sleep(0.5)
        print("You have died: GAME OVER")
elif ch1.lower()=="walk":
    print("You take a stroll around the village, taking extra care to avoid your fields, you don't want to think about work today. As you pass by your neighbors house you see three men struggling with him, clearly trying to rob him, do you...")
    sleep(1)
    print("Continue your WALK and mind your own business")
    sleep(0.5)
    print("Help FIGHT off the robbers")
    sleep(0.5)
    print("DANCE")
    ch2c=input("???: ")
    if ch2c.lower()=="walk":
        print("Your neighbor sees you and calls for help, but you pretend you didn't see. Putting your hands in your pocket you go about your walk and enjoy the stroll. Your neighbor gets robbed and beaten, but you get to enjoy the sun.")
        sleep(1)
        print("Game complete: You got the 'Douche bag' ending. Well done jerk...")
    elif ch2c.lower()=="fight":
        print("You leap into the fight. While two against three is more even than one against three, you're still out numbered and neither of you are armed. You get beaten unconscious after a small scuffle. Once you wake up, do you...")
        sleep(1)
        print("Attempt to TRACK them down")
        sleep(0.5)
        print("Call it a day and go HOME")
        ch3ca=input("???: ")
        if ch3ca.lower()=="track":
            print("You search for clues, nothing. You check for foot prints, nothing. You ask other villagers if they saw anything. One person claims to have seen three rough looking men heading south. Another says they saw someone go from that house to the tavern nearby. Do you...")
            sleep(1)
            print("Go SOUTH")
            sleep(0.5)
            print("Go to the TAVERN")
            ch4caa=input("???: ")
            if ch4caa.lower()=="north":
                print("You head south as far as the forest, but you can't see any evidence anyone's been this way in a long long time, the brush is thick and you see no possible way through. You decide to cut your losses and head home.")
                sleep(7)
                print("Game Complete. You got the 'Victim' ending. Sux 2 B u bro.")
            elif ch4caa.lower()=="tavern":
                print(" 'The tavern sounds nice' you think 'Even if they aren't there, I can drown my sorrows in ale'. When you open the door, you find it to be much livelier than usual. It doesn't seem like there's more people, but the people here are all very excited about something that they're gathered around in a circle. Finding a way to see through the crowd to the middle, you see them!")
                sleep(10)
                print("All three robbers are here, clearly very drunk and looking like they're about to get into a fight. You watch from the sidelines as all three of them get beaten up, with how intoxicated they are they never stood a chance. Swiftly you swoop in and take the gold out of their pockets.")
                sleep(7)
                print("Game Complete! You got the 'Robbery Reversal' ending. What comes around goes around.")
            else:
                print("You are very sad, so very very sad that this happened to you. So sad infact, that you immediately turn to stone.")
                sleep(4)
                print("400 years later, you've been made an exhibit at an art meuseum in St. Louis Missouri, bought for nearly a million dollars. Your value is very high because of how lifelike you are and the fact that nobody knows who the artist is (as there isn't one).")
                sleep(7)
                print("Game Complete! You got the 'High Class' ending. Art majors will be forced to write papers on you for generations to come, and you wouldn't have it any other way.")
        elif ch3ca.lower()=="home":
            print("You're not happy about getting beat like this, but you don't care enough to do anything else, you go home and wallow in your injuries and sadness.")
            sleep(5)
            print("Game Complete. You got the 'Slothful Defender' ending. You tried, but you're too lazy to make it work. Oh well")
        else:
            print("well...")
            sleep(1)
            print("You just...")
            sleep(1)
            print(".")
            sleep(1)
            print(".")
            sleep(1)
            print(".")
            sleep(2)
            print("You just die on the spot")
            sleep(0.5)
            print("You have died: GAME OVER")
    elif ch2c.lower()=="dance":
        print("You can't think of anything else to do, so you bust down dancing. No music is playing, but you can feel the beat in your soul. The robbers are tansfixed with your amazing moves, as is your neighbor. After nearly 20 minutes of dancing, a small croud has gathered. After 45 minutes, you're out of energy and have to stop, but you get a huge cheer from the crowd. The robbers shake hands with your neighbor. Strangers cry tears of joy, arm in arm with people they don't even know. Your moves have brought peace to the land. A man in noble looking clothes approaches you and speaks.")
        print(" 'You dance as if the muses had possesed your feet, the whole world must see this beautiful spectacle. I beg of you, please come with me and dance in the kings court.' Do you...")
        sleep(1)
        print("Say YES")
        sleep(0.5)
        print("Say NO")
        sleep(0.5)
        print("DANCE")
        ch3cb=input("???: ")
        if ch3cb.lower()=="yes":
            print("You're taken to the palace of the high king. The man who offered you the job introduces you to the court and you begin dancing. People give you strange looks as you were meant to wait for the mucisians to begin playing, but once again, you feel the beat in your soul. The mucusians do join in, but it seems not to matter, everyone's attention is totally on you.")
            sleep(10)
            print("You dance and dance. You don't stop when the mucisians stop, you don't stop when the sun sets, your dance isn't finished yet and you can't stop until it is. You keep dancing for well over 8 hours, but the court does not dispurse, they're all transfixed with your amazing dancing and they don't want to miss a single moment.")
            sleep(10)
            print("Finally when you stop, the court explodes into cheers, once again many of them cry for how beautiful your performance was. The king offers you a permanant job here, artsists derive inspiration from you, authors and playwrites make works based on you that are told throughout the ages. You are the best dancer the world has ever seen.")
            sleep(10)
            print("Game Complete! You got the 'Lord of the Dance' ending. Didn't see that one coming did you?")
        elif ch3cb.lower()=="no":
            print("The nobleman begs and pleas with you, he's clearly desparate for this, stating over and over again that your skills must be shared. But you're afraid, afraid that this was a fluke, a one time thing. Word of you spreads far and wide and people from all over the country come to ask you to dance once more, but you refuse every time.")
            sleep(7)
            print("Game Complete. You got the 'One Hit Wonder' ending. You caught the falling star, you put it in your pocket, but unfortunately, you also let it fade away...")
        else:
            print("This decision angers the nobleman, who orders his guards to arrest you for treason. You're thrown in jail where you spend the rest of your days")
            sleep(3)
            print("Many years later, you die in prison.")
            sleep(0.5)
            print("You have died: GAME OVER")
    else:
        print("That was just a stupid answer, why would you write that??? As the game developer I decide that this doesn't work.")
        sleep(3)
        print("You die on the spot")
        sleep(0.5)
        print("You have died: GAME OVER")
else:
    print("Your actions defy meaning or reason, as a result, a vengeful demi-god takes displeasure with you.")
    sleep(3)
    print("You die on the spot")
    sleep(0.5)
    print("You have died: GAME OVER")